plugin:
  id: "export-asap"
  name: "Export ASAP"
  description: "Exports ASAP files from an SDRF file."
  version: "1.0.0"
  category: "utilities"

runtime:
  type: "python"
  script: "export_asap.py"

inputs:
  - name: "sdrf_file"
    label: "SDRF File"
    type: "file"
    required: true
    accept: ".tsv"
    description: "The input SDRF file in .tsv format."

  - name: "asap_team_name"
    label: "ASAP Team Name"
    type: "text"
    default: "Alessi"
    description: "Name of the ASAP team."
  
  - name: "asap_lab_name"
    label: "ASAP Lab Name"
    type: "text"
    default: "Dario Alessi"
    description: "Name of the ASAP lab."

  - name: "pi_full_name"
    label: "PI Full Name"
    type: "text"
    default: "Dario R. Alessi"
    description: "Full name of the Principal Investigator."

  - name: "project_name"
    label: "Project Name"
    type: "text"
    default: ""
  - name: "project_description"
    label: "Project Description"
    type: "text"
    default: ""
  - name: "dataset_title"
    label: "Dataset Title"
    type: "text"
    default: ""
  - name: "dataset_description"
    label: "Dataset Description"
    type: "text"
    default: ""
  - name: "dataset_name"
    label: "Dataset Name"
    type: "text"
    default: ""
  - name: "pi_email"
    label: "PI Email"
    type: "text"
    default: ""
  - name: "contributor_names"
    label: "Contributor Names"
    type: "text"
    default: ""
  - name: "submitter_name"
    label: "Submitter Name"
    type: "text"
    default: ""
  - name: "submitter_email"
    label: "Submitter Email"
    type: "text"
    default: ""
  - name: "asap_grant_id"
    label: "ASAP Grant ID"
    type: "text"
    default: ""
  - name: "other_funding_source"
    label: "Other Funding Source"
    type: "text"
    default: ""
  - name: "publication_doi"
    label: "Publication DOI"
    type: "text"
    default: ""
  - name: "publication_pmid"
    label: "Publication PMID"
    type: "text"
    default: ""
  - name: "number_samples"
    label: "Number of Samples"
    type: "text"
    default: ""
  - name: "sample_types"
    label: "Sample Types"
    type: "text"
    default: ""
  - name: "types_of_samples"
    label: "Types of Samples"
    type: "text"
    default: ""
  - name: "metadata_tables"
    label: "Metadata Tables"
    type: "text"
    default: "SDRF.tsv"
  - name: "dua_version"
    label: "DUA Version"
    type: "text"
    default: ""
  - name: "pi_orcid"
    label: "PI ORCID"
    type: "text"
    default: ""
  - name: "pi_google_scholar_id"
    label: "PI Google Scholar ID"
    type: "text"
    default: ""
  - name: "preprocessing_references"
    label: "Preprocessing References"
    type: "text"
    default: ""
  - name: "metadata_version_date"
    label: "Metadata Version Date"
    type: "text"
    default: ""
  - name: "alternate_dataset_id"
    label: "Alternate Dataset ID"
    type: "text"
    default: ""

outputs:
  - name: "output_dir"
    path: "."

execution:
  argsMapping:
    sdrf_file: "--sdrf_file"
    asap_team_name: "--asap_team_name"
    asap_lab_name: "--asap_lab_name"
    pi_full_name: "--pi_full_name"
    project_name: "--project_name"
    project_description: "--project_description"
    dataset_title: "--dataset_title"
    dataset_description: "--dataset_description"
    dataset_name: "--dataset_name"
    pi_email: "--pi_email"
    contributor_names: "--contributor_names"
    submitter_name: "--submitter_name"
    submitter_email: "--submitter_email"
    asap_grant_id: "--asap_grant_id"
    other_funding_source: "--other_funding_source"
    publication_doi: "--publication_doi"
    publication_pmid: "--publication_pmid"
    number_samples: "--number_samples"
    sample_types: "--sample_types"
    types_of_samples: "--types_of_samples"
    metadata_tables: "--metadata_tables"
    dua_version: "--dua_version"
    pi_orcid: "--pi_orcid"
    pi_google_scholar_id: "--pi_google_scholar_id"
    preprocessing_references: "--preprocessing_references"
    metadata_version_date: "--metadata_version_date"
    alternate_dataset_id: "--alternate_dataset_id"
  outputDir: "--output_dir"

  requirements:
    python: ">=3.8"
    packages:
      - "sdrf_pipelines"
      - "pandas"
